FROM nvcr.io/nvidia/tensorrt:23.05-py3

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PIP_INSTALL="python -m pip --no-cache-dir install --upgrade"

RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
ARG MIRROR_URL="https://mirrors.cernet.edu.cn/ubuntu/"
RUN sed -i "s|http://archive.ubuntu.com/ubuntu/|${MIRROR_URL}|g" /etc/apt/sources.list

RUN apt-get update &&\
    apt-get install -y\
            libgl1-mesa-glx \
            protobuf-compiler \
            libprotoc-dev \
            libb64-0d \
            libturbojpeg \
            python3-opencv \
            ffmpeg &&\
    rm -rf /var/lib/apt/lists/*

COPY requirements-gpu.txt .
RUN pip config set global.index-url https://mirrors.cernet.edu.cn/pypi/web/simple
RUN $PIP_INSTALL -r requirements-gpu.txt

WORKDIR /app
COPY if_rest /app/if_rest
COPY entrypoint.sh /app/entrypoint.sh

ENTRYPOINT [ "bash" ]
CMD ["entrypoint.sh"]
